import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {Header} from "@/components/header";
import {Footer} from "@/components/footer";
import {GhostHeader} from "@/components/frontpage/ghost-header";
import {Hero} from "@/components/frontpage/hero";
import {AboutSection} from "@/components/frontpage/sections/about-section";
import {ServicesSection} from "@/components/frontpage/sections/services-section";
import Link from "next/link";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={"scrollbar-thin"}>
        <body className={inter.className}>
        <div className="drawer drawer-end">
            <input id="my-drawer" type="checkbox" className="drawer-toggle"/>
            {/*Page Content*/}

            <div className="drawer-content">
                <Header/>
                {children}
                <Footer/>
            </div>

            <div className="drawer-side z-50">
                <label htmlFor="my-drawer" aria-label="close sidebar" className="drawer-overlay"></label>
                <ul className="menu bg-base-200 text-base-content min-h-full w-80 p-4 text-lg">
                    <li><Link href={'/'}>Forside</Link></li>
                    <li><Link href={'/behandlinger-og-priser'}>Behandlinger & Priser</Link></li>
                    <li><Link href={'/om-os'}>Om Os</Link></li>
                    <li><Link href={'/kontakt'}>Kontakt</Link></li>
                    <div className="divider"></div>
                    <li><Link href={'/booking'} className={"bg-primary text-primary-content"}>Bestil
                        Tid</Link>
                    </li>
                </ul>
            </div>
        </div>
        </body>
        </html>
    );
}
